/* Remove unique constraint from ECOSYSTEM_ID in IDENTIFIER table */
CREATE TABLE IDENTIFIER_NEW (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATED INTEGER NULL,
    CREATED_TRUSTED INTEGER,
    DELETED INTEGER,
    ECOSYSTEM_ID INTEGER,
    LAST_MODIFIED INTEGER NULL,
    LAST_MODIFIED_TRUSTED INTEGER,
    PATH TEXT);

INSERT INTO IDENTIFIER_NEW
    SELECT * FROM IDENTIFIER;

DROP TABLE IDENTIFIER;
ALTER TABLE IDENTIFIER_NEW RENAME TO IDENTIFIER;
